name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    secrets: inherit
    uses: CrisisCleanup/infrastructure/.github/workflows/deploy.yml@main
